# Generated by Django 2.2.2 on 2020-02-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_caruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='carblock',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='driverblock',
            old_name='DID',
            new_name='Did',
        ),
        migrations.RenameField(
            model_name='driverblock',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='driverbooking',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='lift',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='liftbooking',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='DID',
            new_name='Did',
        ),
        migrations.RenameField(
            model_name='ratings',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='DID',
            new_name='Did',
        ),
        migrations.RenameField(
            model_name='userblock',
            old_name='UID',
            new_name='Uid',
        ),
        migrations.AddField(
            model_name='booking',
            name='CUID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homepage.CarUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carblock',
            name='CUID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homepage.CarUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='CUID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homepage.CarUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caruser',
            name='CUID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
