# Generated by Django 2.2.2 on 2020-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200212_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompany',
            name='CCID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
