# Generated by Django 2.2.2 on 2020-02-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200212_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompany',
            name='CCID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='CCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.CarCompany', unique=True),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='CUID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserData', unique=True),
        ),
    ]
