# Generated by Django 2.2.2 on 2020-02-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200212_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='CCID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.CarCompany'),
        ),
        migrations.AlterField(
            model_name='caruser',
            name='Uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserData'),
        ),
    ]
