# Generated by Django 2.2.2 on 2020-02-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200212_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='CUminfair',
            field=models.CharField(default=50, max_length=10),
        ),
    ]
